### ISSUE TITLE
Migrating models from within QGIS fails

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-modelchecker#144]
### Complexity

moderate

### Priority

high prio

### What happened?

Ik run dit:

`from threedi_modelchecker import ThreediDatabase
from threedi_modelchecker.schema import ModelSchema

version = "head"  # this means 'latest', you can also give it a different version here like 204
sqlite_path = r'C:\modellen\assen-loon-cursus\loon.sqlite'

database = ThreediDatabase(
    connection_settings={"db_path": sqlite_path}, db_type="spatialite"
)
schema = ModelSchema(database)
schema.upgrade(version, backup=False)`

En krijg dit:

```
exec(open('C:/Users/jonas.vanschrojenste/migrate_models.py'.encode('utf-8')).read())
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 104, in upgrade
    v = self.get_version()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 82, in get_version
    connection, opts={"version_table": constants.VERSION_TABLE_NAME}
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 164, in __init__
    log.info("Context impl %s.", self.impl.__class__.__name__)
Message: 'Context impl %s.'
Arguments: ('SQLiteImpl',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 104, in upgrade
    v = self.get_version()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 82, in get_version
    connection, opts={"version_table": constants.VERSION_TABLE_NAME}
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 164, in __init__
    log.info("Context impl %s.", self.impl.__class__.__name__)
Message: 'Context impl %s.'
Arguments: ('SQLiteImpl',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 104, in upgrade
    v = self.get_version()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 82, in get_version
    connection, opts={"version_table": constants.VERSION_TABLE_NAME}
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 171, in __init__
    else "non-transactional",
Message: 'Will assume %s DDL.'
Arguments: ('non-transactional',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 104, in upgrade
    v = self.get_version()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 82, in get_version
    connection, opts={"version_table": constants.VERSION_TABLE_NAME}
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 171, in __init__
    else "non-transactional",
Message: 'Will assume %s DDL.'
Arguments: ('non-transactional',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 115, in upgrade
    _upgrade_database(self.db, revision=revision)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 52, in _upgrade_database
    script.run_env()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 42, in <module>
    run_migrations_online()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 33, in run_migrations_online
    context.configure(connection=connection, target_metadata=target_metadata)
  File "<string>", line 8, in configure
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\environment.py", line 789, in configure
    opts=opts,
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 164, in __init__
    log.info("Context impl %s.", self.impl.__class__.__name__)
Message: 'Context impl %s.'
Arguments: ('SQLiteImpl',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 115, in upgrade
    _upgrade_database(self.db, revision=revision)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 52, in _upgrade_database
    script.run_env()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 42, in <module>
    run_migrations_online()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 33, in run_migrations_online
    context.configure(connection=connection, target_metadata=target_metadata)
  File "<string>", line 8, in configure
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\environment.py", line 789, in configure
    opts=opts,
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 164, in __init__
    log.info("Context impl %s.", self.impl.__class__.__name__)
Message: 'Context impl %s.'
Arguments: ('SQLiteImpl',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 115, in upgrade
    _upgrade_database(self.db, revision=revision)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 52, in _upgrade_database
    script.run_env()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 42, in <module>
    run_migrations_online()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 33, in run_migrations_online
    context.configure(connection=connection, target_metadata=target_metadata)
  File "<string>", line 8, in configure
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\environment.py", line 789, in configure
    opts=opts,
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 171, in __init__
    else "non-transactional",
Message: 'Will assume %s DDL.'
Arguments: ('non-transactional',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console.py", line 653, in runScriptEditor
    self.tabEditorWidget.currentWidget().newEditor.runScriptCode()
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_editor.py", line 460, in runScriptCode
    .format(filename.replace("\\", "/"), sys.getfilesystemencoding()))
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 523, in runCommand
    more = self.runsource(src)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\console\console_sci.py", line 556, in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 74, in runsource
    self.runcode(code)
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 115, in upgrade
    _upgrade_database(self.db, revision=revision)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\schema.py", line 52, in _upgrade_database
    script.run_env()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\script\base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\util\compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 42, in <module>
    run_migrations_online()
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\threedi_modelchecker\migrations\env.py", line 33, in run_migrations_online
    context.configure(connection=connection, target_metadata=target_metadata)
  File "<string>", line 8, in configure
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\environment.py", line 789, in configure
    opts=opts,
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 228, in configure
    return MigrationContext(dialect, connection, opts, environment_context)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\api299_5_en_tb_md023/python\alembic\runtime\migration.py", line 171, in __init__
    else "non-transactional",
Message: 'Will assume %s DDL.'
Arguments: ('non-transactional',)
```

**Comment by Jonasvsl** [comment]
3.16.5

**Comment by caspervdw** [comment]
This is solved by the implementation of Lutra.
