### ISSUE TITLE
Check if the geometry column name is correct before adding spatial indices

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#268]
Example sqlite:
https://management.3di.live/schematisations/4291/45756

The table v2_grid_refinement_area has a geometry column named 'geom' instead of 'the_geom'. 

Of course, users should not mess with the table schema's, but inexperienced users like @Jonasvsl may do all sorts of unexpected stuff and we would really like to help them and make their life better despite this.

When `schema.set_spatial_indexes()` is called, it fails like this:

```
RuntimeError: Spatial index creation for v2_grid_refinement_area_the_geom failed
Traceback (most recent call last):
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_result_selection\result_selection_view.py", line 373, in select_model_spatialite_file
schema.set_spatial_indexes()
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_modelchecker\schema.py", line 269, in set_spatial_indexes
_ensure_spatial_indexes(self.db)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_modelchecker\schema.py", line 121, in _ensure_spatial_indexes
created &= _ensure_spatial_index(connection, geom_columns[0])
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_modelchecker\schema.py", line 102, in _ensure_spatial_index
raise RuntimeError(f"Spatial index creation for {idx_name} failed")
RuntimeError: Spatial index creation for v2_grid_refinement_area_the_geom failed
```

**Comment by leendertvanwolfswinkel** [comment]
See https://github.com/nens/threedi-modelchecker/issues/268
