### ISSUE TITLE
Schematisation checker says friction and infiltration pixel values are wrong, but they are not TOPDESK 2409 0019

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-modelchecker#393]
Modelchecker geeft op productie een error

v2_global_settings.frict_coef_file has values <0 and/or >1 or is empty
v2_simple_infiltration.infiltration_rate_file has values <0 or is empty

Zie https://management.3di.live/schematisations/9681/58835?organisation=61f5a464c35044c19bc7d4b42d7f58cb

Sqlite en rasters zijn nagelopen op fouten; alles lijkt te kloppen, maar dus toch een foutmelding. Hoe kan dit?

**Comment by elisalle** [comment]
Ik krijg een heel andere foutmelding:
```
Traceback (most recent call last):
  File "/home/eli/temp2/venv/bin/threedi_modelchecker", line 8, in <module>
    sys.exit(cli())
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/scripts.py", line 69, in check
    exporters.print_errors(model_errors)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/exporters.py", line 14, in print_errors
    for error in errors:
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/model_checks.py", line 62, in errors
    model_errors = check.get_invalid(session)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/checks/raster.py", line 64, in get_invalid
    return [
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/checks/raster.py", line 67, in <listcomp>
    if path is not None and not self.is_valid(path, raster_interface)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/checks/raster.py", line 293, in is_valid
    raster_min, raster_max = raster.min_max
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/interfaces/raster_interface_gdal.py", line 83, in min_max
    raise e
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/threedi_modelchecker/interfaces/raster_interface_gdal.py", line 78, in min_max
    return self._dataset.GetRasterBand(1).ComputeRasterMinMax(False)
  File "/home/eli/temp2/venv/lib/python3.10/site-packages/osgeo/gdal.py", line 3867, in ComputeRasterMinMax
    return _gdal.Band_ComputeRasterMinMax(self, *args)
RuntimeError: /home/eli/temp2/rasters/friction.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedStrip() failed.
```
Als ik probeer om de minmax via gdal direct uit te lezen via GDAL in een python shell faalt het op zowel friction.tif als infiltration.tif (dem.tif en ini_wl.tif werken wel):
```
from osgeo import gdal
dataset = gdal.Open("friction.tif", gdal.GA_ReadOnly)
dataset.GetRasterBand(1).ComputeRasterMinMax(False)
```
geeft de volgende foutmelding:
```
ERROR 1: PredictorSetup:Horizontal differencing "Predictor" not supported with 64-bit samples
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: friction.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedStrip() failed.
```

**Comment by leendertvanwolfswinkel** [comment]
Was difficult to reproduce, was fixed by creating a new schematisation
